### ISSUE TITLE
Several installation problems

### ISSUE THREAD

**Issue by pladaria** [gfduszynski/cm-rgb#30]
Following installation guide on a fresh linux mint install I got some missing dependency problems

### 1. Missing deps 

Can be installed by executing:
```sh
pip install wheel
pip install enum
```

I don't know much about python ecosystem, perhaps those deps could be added as project dependencies or at least document that in the installation guide

### 2. pip bin dir not in path

I had to manually add it in `.bashrc`

```sh
export PATH="$HOME/.local/bin/:$PATH"
```

### 3. `/usr/bin/sh` not found when executing `cm-rgb-cli add-udev-rule`

```sh
$ cm-rgb-cli add-udev-rule
sudo: /usr/bin/sh: command not found
Failed to create /etc/udev/rules.d/60-cm-rgb.rules
```

Quick & dirty workaround

```
sudo ln -s /bin/sh /usr/bin/sh
```

---

Hope this helps someone

Thanks for your great work!

**Comment by pladaria** [comment]
But after all, I get errors trying to execute example commands:
```
$ cm-rgb-monitor --cpu-color=#FFA500 --bg-color=#00FFFF --show-sensor --low-color=#00FF00 --high-color=#FF0000
Usage: cm-rgb-monitor [OPTIONS]
Try 'cm-rgb-monitor --help' for help.

Error: no such option: --show-sensor
```

```
$ cm-rgb-cli set logo --mode=breathe --color=#00ff00 --speed=3 --brightness=5 fan --mode=breathe --color=#0000ff --speed=4 --brightness=1 ring --mode=swirl --color=#ff0000 --speed=1 --brightness=1
Traceback (most recent call last):
  File "/home/pladaria/.local/bin/cm-rgb-cli", line 151, in <module>
    main_group()
  File "/home/pladaria/.local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pladaria/.local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pladaria/.local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pladaria/.local/lib/python2.7/site-packages/click/core.py", line 1268, in invoke
    Command.invoke(self, ctx)
  File "/home/pladaria/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pladaria/.local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pladaria/.local/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pladaria/.local/bin/cm-rgb-cli", line 13, in setup_group
    'ctrl': CMRGBController(),
  File "/home/pladaria/.local/lib/python2.7/site-packages/cm_rgb/ctrl.py", line 50, in __init__
    self.__init_hid_device()
  File "/home/pladaria/.local/lib/python2.7/site-packages/cm_rgb/ctrl.py", line 60, in __init_hid_device
    self.device.open_path(device_list[0]["path"])
  File "hid.pyx", line 72, in hid.device.open_path
IOError: open failed
```

**Comment by gfduszynski** [comment]
Hi,
Please try ``--show-temp``
I didn't fully update readme yet.
I'll take a look at the installation issue.

**Comment by pladaria** [comment]
```
$ cm-rgb-cli --show-temp
Usage: cm-rgb-cli [OPTIONS] COMMAND [ARGS]...
Try 'cm-rgb-cli --help' for help.

Error: no such option: --show-temp
```

```
$ cm-rgb-monitor --show-temp
Usage: cm-rgb-monitor [OPTIONS]
Try 'cm-rgb-monitor --help' for help.

Error: no such option: --show-temp
```

**Comment by gfduszynski** [comment]
Second issue may be related to access privileges. Perhaps udev rules did not take effect.
Please try running ``chmod 777 <usb device>`` for testing purposes.

**Comment by gfduszynski** [comment]
Please run ``pip show cm-rgb`` I need to verify what version is installed.

**Comment by pladaria** [comment]
```$ pip show cm-rgb
Name: cm-rgb
Version: 0.1.0
Summary: Utility to control RGB on AMD Wraith Prism
Home-page: http://github.com/cm-rgb
Author: gfduszynski
Author-email: gfduszynski@gmail.com
License: MIT
Location: /home/pladaria/.local/lib/python2.7/site-packages
Requires: hidapi, click, psutil
```

**Comment by gfduszynski** [comment]
Run this to upgrade to 0.2.0:
``pip install cm-rgb --upgrade``

**Comment by pladaria** [comment]
```
$ pip install cm-rgb --upgrade
Collecting cm-rgb
Collecting hidapi (from cm-rgb)
Collecting psutil (from cm-rgb)
Collecting click (from cm-rgb)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting setuptools>=19.0 (from hidapi->cm-rgb)
  Using cached https://files.pythonhosted.org/packages/ab/b5/3679d7c98be5b65fa5522671ef437b792d909cf3908ba54fe9eca5d2a766/setuptools-44.1.0-py2.py3-none-any.whl
Installing collected packages: setuptools, hidapi, psutil, click, cm-rgb
Successfully installed click-7.1.2 cm-rgb-0.1.0 hidapi-0.9.0.post2 psutil-5.7.0 setuptools-44.1.0
```

```
$ pip show cm-rgb
Name: cm-rgb
Version: 0.1.0
Summary: Utility to control RGB on AMD Wraith Prism
Home-page: http://github.com/cm-rgb
Author: gfduszynski
Author-email: gfduszynski@gmail.com
License: MIT
Location: /home/pladaria/.local/lib/python2.7/site-packages
Requires: hidapi, click, psutil
```

**Comment by gfduszynski** [comment]
That's highly unusual
https://pypi.org/project/cm-rgb/
There is 0.2.0 in repo, and yet your system chooses older one.

Temp display only works with 0.2.0 btw.

**Comment by pladaria** [comment]
Does this need python2 or 3? (my system has python2 as the default)

**Comment by gfduszynski** [comment]
Try:
`` pip install 'cm-rgb==0.2.0' --force-reinstall``

Should work on both python versions I think.

**Comment by pladaria** [comment]
weird
```$ pip install 'cm0rgb==0.2.0' --force-reinstall
Collecting cm0rgb==0.2.0
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/cm0rgb/
```

If you prefer, we can move this conversation to a chat, my Telegram handle is @pladaria

**Comment by gfduszynski** [comment]
I'm at work now I don't have much time, I'll have more in about 6 hours.
I had a typo there, I wrote "cm0rgb" instead of "cm-rgb"

**Comment by pladaria** [comment]
```
$ pip install 'cm-rgb==0.2.0' --force-reinstall
Collecting cm-rgb==0.2.0
  Could not find a version that satisfies the requirement cm-rgb==0.2.0 (from versions: 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0)
No matching distribution found for cm-rgb==0.2.0
```

Not in a hurry, we can continue later, thanks! ;)

**Comment by gfduszynski** [comment]
In the mean time take a look at this: https://stackoverflow.com/questions/14617136/why-is-pip-installing-an-old-version-of-my-package

**Comment by pladaria** [comment]
Got it

1. uninstall everything
2. `install using pip3` (my pip uses python2)
3. install missing deps `pip3 install xxx` (`wheel`, `pysensors`, maybe others, I don't remember)
4. now I got the right version
5. `cm-rgb-monitor --show-temp` fails but executing with sudo works:
6. ```sudo `which cm-rgb-monitor` --show-temp```

**Comment by gfduszynski** [comment]
Try ``cm-rgb-cli add-udev-rule`` to avoid using sudo

**Comment by pladaria** [comment]
I already did that:

```
$ cat /etc/udev/rules.d/60-cm-rgb.rules 
SUBSYSTEM=="usb", ATTR{idVendor}=="2516", ATTR{idProduct}=="0051", TAG+="uaccess", TAG+="udev-acl"
```

But was still requiring sudo, to avoid that, I had to add myself to the `dialout` group
```
sudo adduser <username> dialout
```
After restarting the session, everything works as expected

As a final note, some commands in README are using different (outdated?) parameter names

Thanks for your quick support!

**Comment by gfduszynski** [comment]
I'm happy it has worked for you.
I'll leave this issue open for now, I'll update wiki on weekend.
