### ISSUE TITLE
OSError: open failed

### ISSUE THREAD

**Issue by JCruk** [gfduszynski/cm-rgb#39]
I just built a new system with a Wraith Prism cooler and stumbled across this fantastic tool in searching for a way to change the colour scheme under Linux. However, I'm getting an `OSError: open failed` error when trying to send commands.

OS is Ubuntu 20.04
Processor AMD Ryzen 7 3800x
MoBo: Gigabyte Aorus x570 Elite

```
user@system:~$ lsusb | grep 2516:0051
Bus 003 Device 003: ID 2516:0051 Cooler Master Co., Ltd. 
```

Command resulting in error:

```
user@system:~$ cm-rgb-cli set logo --mode=static --color=#ff4f00 --brightness=3 fan --mode=static --color=#ff4f00 --brightness=3 ring --mode=static --color=#ff4f00 --brightness=3
Traceback (most recent call last):
  File "/home/user/.local/bin/cm-rgb-cli", line 175, in <module>
    main_group()
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jeff/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1268, in invoke
    Command.invoke(self, ctx)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/bin/cm-rgb-cli", line 13, in setup_group
    'ctrl': CMRGBController(),
  File "/home/user/.local/lib/python3.8/site-packages/cm_rgb/ctrl.py", line 54, in __init__
    self.__init_hid_device()
  File "/home/user/.local/lib/python3.8/site-packages/cm_rgb/ctrl.py", line 64, in __init_hid_device
    self.device.open_path(device_list[0]["path"])
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
```

Please let me know what else I can provide to help debug this issue.

**Comment by gfduszynski** [comment]
Typically this is a permission issue with the usb device.
See wiki  [here](https://github.com/gfduszynski/cm-rgb/wiki/1.-Installation-&-Configuration#3-configuration)

**Comment by JCruk** [comment]
I added the udev rule with:
`cm-rgb-cli add-udev-rule`

Then reloaded udev with:
`sudo udevadm trigger`

But still receive the same errors

**Comment by JCruk** [comment]
I noticed that no udev rule is created:

sudo cm-rgb-cli add-udev-rule

'SUBSYSTEM=="usb", ATTR{idVendor}=="2516", ATTR{idProduct}=="0051", TAG+="uaccess", TAG+="udev-acl"' > /etc/udev/rules.d/60-cm-rgb.rules
Created /etc/udev/rules.d/60-cm-rgb.rules
udev should apply new rule automatically. If not, try running 'sudo udevadm trigger'.
user@system:ls /etc/udev/rules.d
60-vboxdrv.rules  70-snap.snapd.rules

**Comment by gfduszynski** [comment]
That's weird I'll investigate.
Can you try to create the file manually ?

**Comment by lal12** [comment]
Had the same problem. Creating it manually works.

**Comment by gfduszynski** [comment]
I've released new version which I hope should fix the issue.
Please verify if possible as it has been impossible for me to recreate this issue.
