### ISSUE TITLE
ERROR: Could not build wheels for PyGObject which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by abhijay9** [gfduszynski/cm-rgb#45]
Error while installing using pip:
pip install cm-rgb

Processing /home/abhijay/Documents/clones/cm-rgb
Processing /home/abhijay/.cache/pip/wheels/77/e6/04/44ed63e242e5c576da83e0410120d084e9762d1911b1becf38/hidapi-0.9.0.post3-cp37-cp37m-linux_x86_64.whl
Requirement already satisfied: click in /home/abhijay/anaconda3/lib/python3.7/site-packages (from cm-rgb==0.3.4) (7.0)
Requirement already satisfied: psutil in /home/abhijay/anaconda3/lib/python3.7/site-packages (from cm-rgb==0.3.4) (5.6.7)
Collecting PyGObject
  Using cached PyGObject-3.36.1.tar.gz (716 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools>=19.0 in /home/abhijay/anaconda3/lib/python3.7/site-packages (from hidapi->cm-rgb==0.3.4) (49.6.0)
Requirement already satisfied: pycairo>=1.11.1 in /home/abhijay/anaconda3/lib/python3.7/site-packages (from PyGObject->cm-rgb==0.3.4) (1.11.1)
Building wheels for collected packages: cm-rgb, PyGObject
  Building wheel for cm-rgb (setup.py) ... done
  Created wheel for cm-rgb: filename=cm_rgb-0.3.4-py3-none-any.whl size=9216 sha256=4e34f5cc8689ef86432c881b393c48c616bdaa5d0385474d5b5e31cc25017ae0
  Stored in directory: /home/abhijay/.cache/pip/wheels/60/31/da/c35036a9900e2c4067d8083c4b3a0799e89957eacd4b7c0649
  Building wheel for PyGObject (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/abhijay/anaconda3/bin/python /home/abhijay/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpb1nagat8
       cwd: /tmp/pip-install-kka8rmmn/pygobject
  Complete output (91 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/pygtkcompat
  copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.7/pygtkcompat
  copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.7/pygtkcompat
  copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.7/pygtkcompat
  creating build/lib.linux-x86_64-3.7/gi
  copying gi/_constants.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/__init__.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/types.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/module.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/importer.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_error.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_compat.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/docstring.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_option.py -> build/lib.linux-x86_64-3.7/gi
  creating build/lib.linux-x86_64-3.7/gi/repository
  copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.7/gi/repository
  creating build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.7/gi/overrides
  running build_ext
  pycairo: new API
  Traceback (most recent call last):
    File "/home/abhijay/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/abhijay/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/abhijay/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-28fmexef/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-28fmexef/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-28fmexef/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 267, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-28fmexef/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 1288, in <module>
      main()
    File "setup.py", line 1283, in main
      zip_safe=False,
    File "/tmp/pip-build-env-28fmexef/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/home/abhijay/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/abhijay/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/abhijay/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-28fmexef/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/home/abhijay/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/abhijay/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/abhijay/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/abhijay/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/abhijay/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 1118, in run
      self._setup_extensions()
    File "setup.py", line 1110, in _setup_extensions
      add_pycairo(gi_cairo_ext)
    File "setup.py", line 1093, in add_pycairo
      ext.include_dirs += [get_pycairo_include_dir()]
    File "setup.py", line 915, in get_pycairo_include_dir
      include_dir = find_path(find_new_api())
    File "setup.py", line 860, in find_new_api
      import cairo
    File "/tmp/pip-build-env-28fmexef/overlay/lib/python3.7/site-packages/cairo/__init__.py", line 1, in <module>
      from ._cairo import *  # noqa: F401,F403
  ImportError: /tmp/pip-build-env-28fmexef/overlay/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_svg_surface_set_document_unit
  ----------------------------------------
  ERROR: Failed building wheel for PyGObject
Successfully built cm-rgb
Failed to build PyGObject
ERROR: Could not build wheels for PyGObject which use PEP 517 and cannot be installed directly

**Comment by abhijay-g** [comment]
Solved it using:

    python3 -m pip install --no-use-pep517  cm-rgb

**Comment by abhijay9** [comment]
Solved it using:

    python3 -m pip install --no-use-pep517  cm-rgb

**Comment by viren-vii** [comment]
Worked for me ~
`sudo apt install libgirepository1.0-dev`

**Comment by iamzili** [comment]
Hi, I had the same issue. I fixed it via [getting started guide](https://pygobject.readthedocs.io/en/latest/getting_started.html#arch-logo-arch-linux) -  arch distro commands:

- `sudo pacman -S cairo pkgconf gobject-introspection gtk3`
- `pip install PyGObject`
-  success :tada:

**Comment by irik77587** [comment]
looks like windows users have to use [msys2](https://www.msys2.org/) to get [Gtk](https://www.gtk.org/docs/installations/windows/) running. Once msys2 is installed, use mingw64 of msys2 and proceed as stated by [zili55](https://github.com/gfduszynski/cm-rgb/issues/45#issuecomment-920936950)

    pacman -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python mingw-w64-x86_64-python-gobject

**Comment by avatar-lavventura** [comment]
```bash
sudo apt install libgirepository1.0-dev
python3 -m pip install --no-use-pep517 cm-rgb
```

**Comment by barisgungor10** [comment]
> Worked for me ~ `sudo apt install libgirepository1.0-dev`

GOD BLESS YOU
