### ISSUE TITLE
"No devices found" without sudo

### ISSUE THREAD

**Issue by jrhadams** [gfduszynski/cm-rgb#50]
First off, I really love this project. Thank you for your work here.

I've looked through your documentation and believe I've followed the instructions to a T. Unfortunately, it doesn't seem that I can use the cli without sudo level access. I am on a Fedora work station on kernel 5.9.13 with python 3.9.

I understand this is probably related to #4 and you resolved this after the release of v0.1.0, but I'm not sure what the issue could be. Interestingly, if I switch from version v0.3.4 to v0.1.0 I'm able to add the udev rule without an issue but still can't run 'cm-rgb-cli` without sudo. I included some of the output below. 

If I am missing some serious low hanging fruit, please let me know.

```bash
james@fedora-workstation: ~/Programmes/cm-rgb$ cm-rgb-cli set logo --mode=breathe --color=#00ff00 --speed=3 --brightness=5 fan --mode=breathe --color=#0000ff --speed=4 --brightness=1 ring --mode=swirl --color=#ff0000 --speed=1 --brightness=1                                                                   
Traceback (most recent call last):
  File "/home/james/.local/bin/cm-rgb-cli", line 151, in <module>
    main_group()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1268, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/james/.local/bin/cm-rgb-cli", line 13, in setup_group
    'ctrl': CMRGBController(),
  File "/home/james/.local/lib/python3.9/site-packages/cm_rgb/ctrl.py", line 50, in __init__
    self.__init_hid_device()
  File "/home/james/.local/lib/python3.9/site-packages/cm_rgb/ctrl.py", line 57, in __init_hid_device
    raise Exception("No devices found")
Exception: No devices found
```

**Comment by gfduszynski** [comment]
Hi :)

Let's first verify udev rule. Please check if the file exists (/etc/udev/rules.d/90-cm-rgb.rules on my system) and paste it's contents just to be sure.

**Comment by jrhadams** [comment]
Thanks for your prompt reply! 

It seems that I have no rules under 90-cm-rgb.rules. The rule appears to have been added under 60-cm-rgb.rules.

```bash
james@fedora-workstation: ~$ cat /etc/udev/rules.d/60-cm-rgb.rules 
SUBSYSTEM=="usb", ATTR{idVendor}=="2516", ATTR{idProduct}=="0051", TAG+="uaccess", TAG+="udev-acl"
```

**Comment by gfduszynski** [comment]
Ok, here are couple of thing to try:

1) Check if the rule is getting triggered (https://superuser.com/questions/677106/how-to-check-if-a-udev-rule-fired)
2) If the rule is not triggered, change file name to 90-cm-rgb.rules which will alter the order, restart udev go to step 1.
