### ISSUE TITLE
please go through this error

### ISSUE THREAD

**Issue by deletedaccount00** [gfduszynski/cm-rgb#58]
Traceback (most recent call last):
  File "/usr/local/bin/cm-rgb-cli", line 181, in <module>
    main_group()
  File "/home/user1/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user1/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user1/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user1/.local/lib/python3.7/site-packages/click/core.py", line 1268, in invoke
    Command.invoke(self, ctx)
  File "/home/user1/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user1/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user1/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/bin/cm-rgb-cli", line 13, in setup_group
    'ctrl': CMRGBController(),
  File "/home/user1/.local/lib/python3.7/site-packages/cm_rgb/ctrl.py", line 54, in __init__
    self.__init_hid_device()
  File "/home/user1/.local/lib/python3.7/site-packages/cm_rgb/ctrl.py", line 61, in __init_hid_device
    raise Exception("No devices found. See: https://github.com/gfduszynski/cm-rgb/issues/9")
Exception: No devices found. See: https://github.com/gfduszynski/cm-rgb/issues/9

**Comment by gfduszynski** [comment]
Hi, 
Have you checked #9 ?
